### ISSUE TITLE
repo does not allow pull requests

### ISSUE THREAD

**Issue by ericherman** [briandfoy/dumbbench#1]
Question: can github pull requests be created between two git repos if they were created externally rather than using githubs "fork" GUI interface? I would expect that "Compare across forks" to allow for this, but seemingly not. Or am I holding it wrong?

https://github.com/briandfoy/dumbbench seems to have been uploaded to github without using the GUI "fork" feature.

The repo ericherman/dumbbench was forked from tsee/dumbbench -- pull requests work there.

If github's cross-fork features are not sophisticated enough to deal with externally uploaded identical repos, and if github's briandfoy/dumbbench is the new authority repo for dumbbench, perhaps it makes sense to re-create it on github as a fork of tsee/dumbbench such that existing forks from tsee can create pull requests to briandfoy. What do you think?

**Comment by briandfoy** [comment]
This is the main repo. If you want to send pull requests you can fork this repo, apply your changes, and then send a pull request.
