### ISSUE TITLE
align rate and precision separately in report

### ISSUE THREAD

**Issue by y** [briandfoy/dumbbench#4]
each line of the report can have a different number of significant digits for both the rate and the precision, so the values in the report don't line up and this makes it harder than it should be to compare the results. the easiest approach might be to have an option to disable showing the precision.

example from Benchmark::Dumb pod:

                          Rate        b      a
         b   5.75e+06+-47000/s       -- -70.1%
         a 1.925e+07+-650000/s 235+-12%     --

**Comment by briandfoy** [comment]
This is done in 0.501. This also inserts a column in the results for cmpthese.
