### ISSUE TITLE
box_plot() should indicate failure to load Dumbbench::BoxPlot

### ISSUE THREAD

**Issue by FGasper** [briandfoy/dumbbench#6]
I’m following the POD, which seems to indicate that box_plot()->show() should be a drop-in replacement for report(), but box_plot() is returning undef.

Is that envisioned? I’m assuming there’s a bug somewhere …

Thank you!

**Comment by FGasper** [comment]
Update: I looked at the code, and apparently it’s deliberately silencing error reports … ??

This seems like it should allow the exception to propagate—since what I asked to do (create the box plot) can’t be done—or at least warn() when there is an error.

**Comment by briandfoy** [comment]
I think this is related to the undeclared dependency on SOOT, which is on purpose. It's not a trivial install and it's the only reason why I think loading the module can fail. I think that error should be propagated. At the application level, you'll still have to catch the error of calling a method undef, so you might as well catch it on not loading. In #5 I adjusted the loading of SOOT to catch the error and give a better message. (879af9faf05575a11c799acfad26b022a22ce30f)
