### ISSUE TITLE
what unit are the measurements reported in?

### ISSUE THREAD

**Issue by karenetheridge** [briandfoy/dumbbench#8]
For results like `Rounded run time per iteration: 2.3207e+00 +/- 8.4e-03 (0.4%)` -- what unit is this runtime reported in? Given that they are *per iteration*, are they milliseconds? Or perhaps microseconds (µs)?

**Comment by briandfoy** [comment]
The timing is in seconds, so I've added that to the output string (8f04e7bd8f357f1866b28962f8439598477a3dde).

```
$ cat tester.pl
#!/usr/bin/perl
sleep 3;
```

```
$ perl -Ilib bin/dumbbench ./tester.pl
cmd: Ran 20 iterations (0 outliers).
cmd: Rounded run time per iteration (seconds): 3.01041e+00 +/- 2.5e-04 (0.0%)
```
