### ISSUE TITLE
LICENSE inconsistencies

### ISSUE THREAD

**Issue by kentfredric** [briandfoy/dumbbench#9]
https://github.com/briandfoy/dumbbench/blob/490bac1eac2e8f4cfcd832649523f8517c7ef151/LICENSE#L1-L7

https://github.com/briandfoy/dumbbench/blob/490bac1eac2e8f4cfcd832649523f8517c7ef151/Makefile.PL#L52

https://github.com/briandfoy/dumbbench/blob/490bac1eac2e8f4cfcd832649523f8517c7ef151/lib/Dumbbench.pm#L538-L540

( And in fact, all modules site the same perl5- license blurb )

Thus, it seems the error  is the LICENSE file itself having the wrong content.

**Comment by briandfoy** [comment]
Yeah, that's my fault for adding the LICENSE file. I've fixed that in the repo and it will be in the next release. Thanks for noticing.
